### ISSUE TITLE
Communicate the attitude of the initiative

### ISSUE THREAD

**Issue by antaranyan** [despan/machina#1]
Clarify the scope and context for for other contributors.

* What _the initiative_ aims to achieve
* When and why it may be useful

Use common communication channels, i.e. [community health files](https://help.github.com/en/articles/about-community-profiles-for-public-repositories)

* [ ]  Answer mentioned questions in _README_
* [ ]  Outline the _roadmap_
* [ ]  Define _contributing guidelines_
* [ ]  Declare _code of conduct_
* [ ]  Add an open-source license
* [ ]  Improvise

### Acceptance criteria
Doesn't have to be exhaustive or final, needed as a baseline for later enhancement.

### Useful references
* [makeareadme.com](https://www.makeareadme.com/)
* [mozilla.github.io/open-leadership-training-series/articles/readme](https://mozilla.github.io/open-leadership-training-series/articles/readme/)
  [mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/)
* [mozillascience.github.io/working-open-workshop/contributing](https://mozillascience.github.io/working-open-workshop/contributing/)
* [ContributorCovenant/contributor_covenant](https://github.com/ContributorCovenant/contributor_covenant)
